### ISSUE TITLE
could not connect to mlab mongodb

### ISSUE THREAD

**Issue by sushilldhakal** [huynhsamha/dontpad#14]
### Actual behavior
MongoNetworkError: failed to connect to server

### Steps to reproduce the behavior
added uri from mlab to .env file

**Comment by huynhsamha** [comment]
Hi @sushilldhakal ,
Thank for your issue to my repository.

With your problem, you should make sure that file `.env` such as `.env.example`, that is:

```
URI_MONGO="mongodb://<db_username>:<db_password>@<domain>:<port>/<db_name>"
```

If you use mlab, you should create a new user in tab `Users` on mlab

![img](https://user-images.githubusercontent.com/24195776/70206494-4fb55200-175a-11ea-8f97-8c5d58171824.jpg)

You can also connect to mongo using mongo shell.

**Comment by sushilldhakal** [comment]
@huynhsamha mlab has closed to the new account creation, so it redirects to cloud.mongodb.com. I have added the link provided by cloud.mongodb.com in .env file which is giving me this error.

MongoNetworkError: failed to connect to server [savetext-shard-00-02-tsi3m.mongodb.net:27017] on first connect [MongoNetworkError: connection 5 to savetext-shard-00-02-tsi3m.mongodb.net:27017 closed

**Comment by huynhsamha** [comment]
@sushilldhakal Have you tried connecting to Mongo using mongo shell?

I think the problem is connection to your mongo cluster, you should make sure you can connect to your cluster.

I have created new cluster on cloud.mongodb.com and connect to it using mongo shell successfully.

<img width="804" alt="Screen Shot 2019-12-25 at 7 37 31 AM" src="https://user-images.githubusercontent.com/24195776/71427275-74fa0800-26e9-11ea-889a-2cf6c6357d7d.png">
